import type { WordPair } from "./types";

export const WORD_PAIRS: readonly WordPair[] = [
  { civilian: "Café", undercover: "Thé" },
  { civilian: "Plage", undercover: "Désert" },
  { civilian: "Médecin", undercover: "Vétérinaire" },
  { civilian: "Chien", undercover: "Loup" },
  { civilian: "Chat", undercover: "Tigre" },
  { civilian: "Pomme", undercover: "Poire" },
  { civilian: "Voiture", undercover: "Moto" },
  { civilian: "Train", undercover: "Métro" },
  { civilian: "Avion", undercover: "Hélicoptère" },
  { civilian: "Football", undercover: "Rugby" },
  { civilian: "Tennis", undercover: "Badminton" },
  { civilian: "Piano", undercover: "Guitare" },
  { civilian: "Violon", undercover: "Alto" },
  { civilian: "Livre", undercover: "Magazine" },
  { civilian: "Stylo", undercover: "Crayon" },
  { civilian: "Été", undercover: "Hiver" },
  { civilian: "Soleil", undercover: "Lune" },
  { civilian: "Mer", undercover: "Océan" },
  { civilian: "Lac", undercover: "Étang" },
  { civilian: "Rivière", undercover: "Fleuve" },
  { civilian: "Montagne", undercover: "Colline" },
  { civilian: "Forêt", undercover: "Jungle" },
  { civilian: "Pizza", undercover: "Quiche" },
  { civilian: "Croissant", undercover: "Pain au chocolat" },
  { civilian: "Baguette", undercover: "Brioche" },
  { civilian: "Fromage", undercover: "Yaourt" },
  { civilian: "Vin", undercover: "Bière" },
  { civilian: "Champagne", undercover: "Cidre" },
  { civilian: "Chocolat", undercover: "Caramel" },
  { civilian: "Glace", undercover: "Sorbet" },
  { civilian: "Boulanger", undercover: "Pâtissier" },
  { civilian: "Professeur", undercover: "Instituteur" },
  { civilian: "Pompier", undercover: "Policier" },
  { civilian: "Architecte", undercover: "Ingénieur" },
  { civilian: "Acteur", undercover: "Chanteur" },
  { civilian: "Roi", undercover: "Empereur" },
  { civilian: "Prince", undercover: "Duc" },
  { civilian: "Sorcier", undercover: "Magicien" },
  { civilian: "Vampire", undercover: "Zombie" },
  { civilian: "Fantôme", undercover: "Esprit" },
  { civilian: "Soleil", undercover: "Étoile" },
  { civilian: "Pluie", undercover: "Neige" },
  { civilian: "Orage", undercover: "Tempête" },
  { civilian: "Arc-en-ciel", undercover: "Aurore boréale" },
  { civilian: "Vélo", undercover: "Trottinette" },
  { civilian: "Skateboard", undercover: "Rollers" },
  { civilian: "Bateau", undercover: "Voilier" },
  { civilian: "Canoë", undercover: "Kayak" },
  { civilian: "Téléphone", undercover: "Tablette" },
  { civilian: "Ordinateur", undercover: "Console" },
  { civilian: "Télévision", undercover: "Cinéma" },
  { civilian: "Photo", undercover: "Tableau" },
  { civilian: "Sculpture", undercover: "Statue" },
  { civilian: "Pyramide", undercover: "Temple" },
  { civilian: "Château", undercover: "Palais" },
  { civilian: "Maison", undercover: "Appartement" },
  { civilian: "Jardin", undercover: "Parc" },
  { civilian: "Cuisine", undercover: "Salle à manger" },
  { civilian: "Lit", undercover: "Canapé" },
  { civilian: "Miroir", undercover: "Fenêtre" },
  { civilian: "Lampe", undercover: "Bougie" },
  { civilian: "Chemise", undercover: "T-shirt" },
  { civilian: "Pantalon", undercover: "Short" },
  { civilian: "Robe", undercover: "Jupe" },
  { civilian: "Manteau", undercover: "Veste" },
  { civilian: "Chaussure", undercover: "Botte" },
  { civilian: "Chapeau", undercover: "Casquette" },
  { civilian: "Sac à main", undercover: "Sac à dos" },
  { civilian: "Bague", undercover: "Bracelet" },
  { civilian: "Collier", undercover: "Pendentif" },
  { civilian: "Lunettes", undercover: "Masque" },
  { civilian: "Carotte", undercover: "Navet" },
  { civilian: "Tomate", undercover: "Poivron" },
  { civilian: "Salade", undercover: "Épinard" },
  { civilian: "Champignon", undercover: "Truffe" },
  { civilian: "Poulet", undercover: "Dinde" },
  { civilian: "Bœuf", undercover: "Veau" },
  { civilian: "Saumon", undercover: "Truite" },
  { civilian: "Crevette", undercover: "Langoustine" },
  { civilian: "Citron", undercover: "Orange" },
  { civilian: "Banane", undercover: "Plantain" },
  { civilian: "Fraise", undercover: "Framboise" },
  { civilian: "Raisin", undercover: "Cerise" },
  { civilian: "Boxe", undercover: "Karaté" },
  { civilian: "Yoga", undercover: "Pilates" },
  { civilian: "Marathon", undercover: "Triathlon" },
  { civilian: "Natation", undercover: "Plongée" },
  { civilian: "Ski", undercover: "Snowboard" },
  { civilian: "Halloween", undercover: "Carnaval" },
  { civilian: "Noël", undercover: "Pâques" },
  { civilian: "Mariage", undercover: "Fiançailles" },
  { civilian: "Anniversaire", undercover: "Baptême" },
  { civilian: "Avocat", undercover: "Notaire" },
  { civilian: "Boulangerie", undercover: "Pâtisserie" },
  { civilian: "Aéroport", undercover: "Gare" },
  { civilian: "Hôpital", undercover: "Clinique" },
  { civilian: "Université", undercover: "École" },
  { civilian: "Bibliothèque", undercover: "Librairie" },
  { civilian: "Musée", undercover: "Galerie" },
  { civilian: "Restaurant", undercover: "Brasserie" },
  { civilian: "Hôtel", undercover: "Auberge" },
  { civilian: "Banque", undercover: "Bureau de poste" },
];

export function pickRandomWordPair(): WordPair {
  const pair = WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
  if (Math.random() < 0.5) {
    return { civilian: pair.undercover, undercover: pair.civilian };
  }
  return pair;
}
